// This data is rendered by the Vue.js JavaScript Framework
// https://vuejs.org/

// Projects Gallery data
const projects = [
	{
		url: 'https://lifechurchmonroe.org',
		image: 'img/LifeChurchMonroe.JPG',
		alt: 'LifeChurchMonroe.org',
		description: 'LifeChurchMonroe.org - A Church Website that contains a directory, photo galleries, tool-tips and map'
	},
	{
		url: 'https://space-station-capstone.herokuapp.com/',
		image: 'img/ISS.jpg',
		alt: 'Space Station',
		description: 'Capstone Project - Tracking the International Space Station using the MERN Stack'
	},
	{
		url: 'https://github.com/severude/Course-Rating-API',
		image: 'img/Postman.JPG',
		alt: 'Course-Rating',
		description: 'A REST API which lets users create, edit and rate courses on the back-end using a Mongo database and Express'
	},
	{
		url: 'https://github.com/severude/Library-Manager',
		image: 'img/Library-Manager.JPG',
		alt: 'Library-Manager',
		description: 'Uses a Sqlite database, Node and Express to search, update and add items to a library app'
	},
	{
		url: 'https://github.com/severude/Gallery-App',
		image: 'img/Flickr.JPG',
		alt: 'Gallery-App',
		description: 'A photo gallery app that searches for photos using the React framework and the Flickr API'
	},
	{
		url: 'https://github.com/severude/Gulp-Build',
		image: 'img/Gulp.jpg',
		alt: 'Gulp-Build',
		description: 'A quick and efficient professional workflow using JavaScript, npm and Node'
	},
	{
		url: 'https://github.com/severude/Twitter-Interface',
		image: 'img/Twitter.jpg',
		alt: 'Twitter-Interface',
		description: 'Uses Node.js and Express to retrieve information from your Twitter account'
	},
	{
		url: 'https://github.com/severude/Content-Scraper',
		image: 'img/Content-Scraping.JPG',
		alt: 'Content-Scraper',
		description: "Node.js command line app that uses npm packages to scrape a website and put it's contents into a CSV file"
	},
	{
		url: 'https://severude.github.io/Employee-Directory',
		image: 'img/EmployeeDirectory.JPG',
		alt: 'Employee-Directory',
		description: 'An employee directory and dynamic modal which is created from an AJAX call to a third-party API'
	},
	{
		url: 'https://severude.github.io/Tic-Tac-Toe',
		image: 'img/TicTacToe.JPG',
		alt: 'Tic-Tac-Toe',
		description: 'Play a Tic-Tac-Toe game against the computer.  Uses object-oriented programming principles for data modeling'
	},
	{
		url: 'https://severude.github.io/Interactive-Form',
		image: 'img/InteractiveForm.JPG',
		alt: 'Interactive-Form',
		description: 'Form validation that is engaging, interactive, and easy to use for the user'
	},
	{
		url: 'https://severude.github.io/Pagination-Filter',
		image: 'img/PaginationFilter.JPG',
		alt: 'Pagination-Filter',
		description: 'Student listings are dynamically divided into pages with a search button for filtering'
	},
	{
		url: 'https://severude.github.io/Quote-Generator',
		image: 'img/QuoteGenerator.JPG',
		alt: 'Quote-Generator',
		description: 'A randomly selected quote is generated by user clicks or after 15 seconds'
	},
	{
		url: 'https://severude.github.io/weather-api',
		image: 'img/Weather.JPG',
		alt: 'weather-api',
		description: 'Retrieve the current weather conditions and forecast for your area'
	},
	{
		url: 'https://severude.github.io/state-capitals',
		image: 'img/50-States.JPG',
		alt: 'state-capitals',
		description: 'Test your knowledge of United States state capitals by taking this quiz'
	},
	{
		url: 'https://severude.github.io/robot-maze',
		image: 'img/RobotMaze.JPG',
		alt: 'robot-maze',
		description: 'Watch your robot navigate through a maze by following along the wall'
	},
	{
		url: 'https://severude.github.io/drawing-app',
		image: 'img/Drawing-App.JPG',
		alt: 'drawing-app',
		description: 'Draw on a canvas with different colors and pen widths'
	},
	{
		url: 'https://severude.github.io/dancing-stars',
		image: 'img/Dancing-Stars.JPG',
		alt: 'dancing-stars',
		description: 'Animation of stars by using CSS animations of SVG objects'
	}
];

// Workflow tools data
const tools = [
	{
		skill: 'HTML',
		url: 'https://developer.mozilla.org/en-US/docs/Web/HTML'
	},
	{
		skill: 'CSS',
		url: 'https://developer.mozilla.org/en-US/docs/Web/CSS'
	},
	{
		skill: 'JavaScript',
		url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript'
	},
	{
		skill: 'WordPress',
		url: 'https://codex.wordpress.org'
	},
	{
		skill: 'Bootstrap',
		url: 'http://v4-alpha.getbootstrap.com'
	},
	{
		skill: 'C#',
		url: 'https://docs.microsoft.com/en-us/dotnet/csharp'
	}
];

// Vue for projects gallery
let gallery = new Vue({
	el: '#gallery',
	data: {
		projects: projects
	}
});

// Vue for workflow tools
let workflow = new Vue({
	el: '.my-buttons',
	data: {
		tools: tools
	}
});
