// This data is rendered by the Vue.js JavaScript Framework
// https://vuejs.org/

// Projects Gallery data
const projects = [
	{
		url: 'https://space-station-capstone.herokuapp.com/',
		image: 'img/ISS.jpg',
		alt: 'Space Station',
		description: 'A Full Stack Application which tracks the International Space Station using Mongo, Express, React and Node'
	},
	{
		url: 'https://github.com/severude/Course-Rating-API',
		image: 'img/Postman.JPG',
		alt: 'Course-Rating',
		description: 'A REST API which lets users create, edit and rate courses on the back-end using a Mongo database and Express'
	},
	{
		url: 'https://github.com/severude/Library-Manager',
		image: 'img/Library-Manager.JPG',
		alt: 'Library-Manager',
		description: 'Uses a Sqlite database, Node and Express to search, update and add items to a library app'
	},
	{
		url: 'https://github.com/severude/Gallery-App',
		image: 'img/Flickr.JPG',
		alt: 'Gallery-App',
		description: 'A photo gallery app that searches for photos using the React framework and the Flickr API'
	},
	{
		url: 'https://github.com/severude/Gulp-Build',
		image: 'img/Gulp.jpg',
		alt: 'Gulp-Build',
		description: 'A quick and efficient professional workflow using JavaScript, npm and Node'
	},
	{
		url: 'https://github.com/severude/Twitter-Interface',
		image: 'img/Twitter.jpg',
		alt: 'Twitter-Interface',
		description: 'Uses Node.js and Express to retrieve information from your Twitter account'
	},
	{
		url: 'https://github.com/severude/Content-Scraper',
		image: 'img/Content-Scraping.JPG',
		alt: 'Content-Scraper',
		description: "Node.js command line app that uses npm packages to scrape a website and put it's contents into a CSV file"
	},
	{
		url: 'https://severude.github.io/Employee-Directory',
		image: 'img/EmployeeDirectory.JPG',
		alt: 'Employee-Directory',
		description: 'An employee directory and dynamic modal which is created from an AJAX call to a third-party API'
	},
	{
		url: 'https://severude.github.io/Tic-Tac-Toe',
		image: 'img/TicTacToe.JPG',
		alt: 'Tic-Tac-Toe',
		description: 'Play a Tic-Tac-Toe game against the computer.  Uses object-oriented programming principles for data modeling'
	},
	{
		url: 'https://severude.github.io/Interactive-Form',
		image: 'img/InteractiveForm.JPG',
		alt: 'Interactive-Form',
		description: 'Form validation that is engaging, interactive, and easy to use for the user'
	},
	{
		url: 'https://severude.github.io/Pagination-Filter',
		image: 'img/PaginationFilter.JPG',
		alt: 'Pagination-Filter',
		description: 'Student listings are dynamically divided into pages with a search button for filtering'
	},
	{
		url: 'https://severude.github.io/Quote-Generator',
		image: 'img/QuoteGenerator.JPG',
		alt: 'Quote-Generator',
		description: 'A randomly selected quote is generated by user clicks or after 15 seconds'
	}
];

// Other projects
const sites = [
	{
		url: 'https://lifechurchmonroe.org',
		image: 'img/LifeChurchMonroe.JPG',
		alt: 'LifeChurchMonroe.org',
		description: 'LifeChurchMonroe.org - This is a large WordPress site that has more than 20 pages built out'
	},
	{
		url: 'https://severude.github.io/weather-api',
		image: 'img/Weather.JPG',
		alt: 'weather-api',
		description: 'An app to retrieve the current weather conditions and forecast for your area'
	},
	{
		url: 'https://severude.github.io/state-capitals',
		image: 'img/50-States.JPG',
		alt: 'state-capitals',
		description: 'This is a quiz for testing your knowledge of United States state capitals'
	}
];

// Skills data
const skills = [
	{
		skill: 'JavaScript',
		url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript'
	},
	{
		skill: 'Node',
		url: 'https://nodejs.org/en'
	},
	{
		skill: 'React',
		url: 'https://reactjs.org'
	},
	{
		skill: 'Express',
		url: 'https://expressjs.com'
	},
	{
		skill: 'MongoDB',
		url: 'https://www.mongodb.com'
	},
	{
		skill: 'SQL',
		url: 'http://docs.sequelizejs.com'
	},
	{
		skill: 'HTML',
		url: 'https://developer.mozilla.org/en-US/docs/Web/HTML'
	},
	{
		skill: 'CSS',
		url: 'https://developer.mozilla.org/en-US/docs/Web/CSS'
	},
	{
		skill: 'Bootstrap',
		url: 'https://getbootstrap.com'
	}
];

// Vue for projects gallery
let gallery = new Vue({
	el: '#gallery',
	data: {
		projects: projects
	}
});

// Vue for websites
let websites = new Vue({
	el: '#sites',
	data: {
		sites: sites
	}
});

// Vue for job skills
let workflow = new Vue({
	el: '.my-buttons',
	data: {
		skills: skills
	}
});
